AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength: 
  Max: 30

Metrics/AbcSize:
  Max: 55 # Or any value that you find suitable

